---

- name: locate shared/config and list of Liberty servers
  command: "{{ wa_target_path }}/bin/server list"
  register: server_list

- name: pick up the lines we are interested in.
  set_fact:
    important_lines: "{{ important_lines|default([]) + [item] }}"
  when: item | length > 1
  with_items:
  - "{{ server_list.stdout_lines }}"

- name: find the line with the name we are looking for 
  set_fact:
    usr_dir: "{{ item }}"
  when: item|trim|lower is search('directory')
  with_items:
  - "{{ important_lines }}"

- name: find the servers
  set_fact:
    liberty_servers: "{{ liberty_servers|default([]) + [item] }}"
  when: item|trim is not search(' ')
  with_items:
  - "{{ important_lines }}"

- name: liberty servers
  debug: 
    msg: "{{ liberty_servers }}"

- name: find the lengths
  set_fact:
    usr_dir_index: "{{ usr_dir.find('directory')|int+10 }}"
    usr_dir_len: "{{ usr_dir|length|int-1 }}"

- name: find the liberty usr dir
  set_fact:
   liberty_usr_dir: "{{ usr_dir[usr_dir_index|int:usr_dir_len|int] }}"
   liberty_shared_config: "{{ usr_dir[usr_dir_index|int:usr_dir_len|int] }}/shared/config"

- name: ensure the liberty shared directory exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ liberty_shared_config }}"

- name: remove existing config
  file:
   path: "{{ item }}"
   state: absent
  with_items:
  - "{{ liberty_shared_config }}/was-usage-metering.xml"
  - "{{ liberty_shared_config }}/was-usage-metering.p12"
  - "{{ liberty_shared_config }}/wa.pem"

- name: find the securityUtility
  command: "find . -name securityUtility"
  args:
   chdir: "{{ wa_target_path }}"
  register: securityUtility_bin

- name: mask the password
  command: "{{ wa_target_path }}/{{ securityUtility_bin.stdout_lines[0] }} encode {{ wa_keystore_pass }}"
  register: xor # DO NOT CHANGE THIS NAME. ITS used in templates/was-usage-metering.xml.j2

- name: find the keytool
  command: "find . -name keytool"
  args:
   chdir: "{{ wa_target_path }}"
  register: keytool_bin

- name: generate new p12 trust
  command: "{{ wa_target_path }}/{{ keytool_bin.stdout_lines[0] }} -genkeypair -dname 'cn=NEST, ou=SVT, o=IBM, c=US' -alias wa -keypass {{ wa_keystore_pass }} -keystore was-usage-metering.p12 -storepass {{ wa_keystore_pass }} -validity 3650 -keyalg RSA -storetype PKCS12"
  args:
   chdir: "{{ liberty_shared_config }}"
  register: genp12

- name: debug wa_cert
  debug: 
    msg: "{{ wa_cert }}"

- name: create input pem file
  template:
   src: wa.pem.j2 # current base64 encoded cert is in defaults/main.yml
   dest: "{{ liberty_shared_config }}/wa.pem"

- name: import wa cert
  command: "{{ wa_target_path }}/{{ keytool_bin.stdout_lines[0] }} -import -trustcacerts -file wa.pem -keystore was-usage-metering.p12 -storepass {{ wa_keystore_pass }} -storetype PKCS12 -noprompt"
  args:
   chdir: "{{ liberty_shared_config }}"
  register: import_cert

- name: Generate config files
  template:
   src: was-usage-metering.xml.j2
   dest: "{{ liberty_shared_config }}/was-usage-metering.xml"

- name: add new config into the servers server.xml file
  lineinfile:
    path: "{{ liberty_usr_dir }}/servers/{{ item }}/server.xml"
    regexp: '^was-usage-metering.xml'
    insertbefore: '</server>'
    line: '     <include optional="true" location="${shared.config.dir}/was-usage-metering.xml" />'
  with_items:
  - "{{ liberty_servers }}"

- block:
  - name: stop liberty servers ( if server not running an error will be produced - ignore and no_log )
    command: "{{ wa_target_path }}/bin/server stop {{ item }}"
    register: stop_server_servers
    ignore_errors: true
    no_log: true
    with_items:
    - "{{ liberty_servers }}"

      #  - name: stop server stdout ( too much output )
      #    debug:
      #     msg: "The command ({{ item.cmd }}) succeeded"
      #    when: item.rc == 0
      #    loop: "{{ stop_server_servers.results }}"

  - name: start liberty servers
    # must use nohup else the server stops after the controller process exits
    command: "nohup {{ wa_target_path }}/bin/server start {{ item }} --clean"
    register: start_server_servers
    with_items:
    - "{{ liberty_servers }}"

      #  - name: start server stdout ( too much output )
      #    debug:
      #     msg: "The command ({{ item.cmd }}) succeeded"
      #    when: item.rc == 0
      #    loop: "{{ start_server_servers.results }}"
  when: startServers == 'true'

