---
- name: Provision OCP Cluster
  hosts: all
  vars_files:
    - common-vars.yml
    - "{{ cloud }}-vars.yml"

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
    PATH: ".:{{ ansible_env.PATH }}"

  roles:
    # used to login into RHACM/HIVE cluster
    - role: ocp_login
    - role: aws_route53
      when: 'cloud == "vsphere" and admin_task != "delete"'
    - role: provision_ocp_cluster
    - role: ocp_cluster_tag
      when: 'admin_task == "provision" and cloud != "vsphere"'
  tasks:
    - set_fact:
        route_task: "delete"
      when: 'cloud == "vsphere" and admin_task == "delete"'

    - name: Run aws_route53 delete - vsphere only
      include_role:
        name: aws_route53
      when: 'cloud == "vsphere" and route_task == "delete"'
