---
    collections:
      - name: community.general
        source: https://galaxy.ansible.com
      - name: community.aws
        source: https://galaxy.ansible.com
      - name: google.cloud
        source: https://galaxy.ansible.com
