---

# blindly try fuser ( linux )
- name:  blindly try fuser ( linux )
  ignore_errors: true
  shell: "fuser -k {{ item }}"
  register: killOutput
  failed_when: ( killOutput.rc not in [ 0, 1, 2, 127 ] )
  with_items:
  - "{{ install_ihs_base }}/{{ http_dir }}"

- name: check if previous ihs installed
  stat:
   path: "{{install_ihs_base }}/{{ http_dir }}/bin/apachectl"
  register: isihs

- name:  stop httpd
  ignore_errors: true
  shell: "{{install_ihs_base }}/{{ http_dir }}/bin/apachectl stop"
  when: isihs.stat.exists == True

- name:  stop adminctl
  ignore_errors: true
  shell: "{{install_ihs_base }}/{{ http_dir }}/bin/adminctl stop"
  when: isihs.stat.exists == True


- name:  stop any running servers
  ignore_errors: true
  shell: "{{ wlp_cmd }} {{install_ihs_base }}/{{ liberty_dir }}/bin/server stop {{ item }}"
  register: stopOutput
  failed_when: ( stopOutput.rc not in [ 0, 2, 23, 127 ] )
  with_items:
  - "{{ wl_server }}"
  - "{{ cc_server }}"
  when: islib.stat.exists == True

- name:  uninstall liberty 
  ignore_errors: true
  shell: "{{ install_ihs_base }}/IM/eclipse/tools/imcl uninstallAll"
  register: uninstallOutput
  failed_when: ( uninstallOutput.rc not in [ 0, 1 ] )
  
- name: uninstallAll output
  debug: 
   msg: "{{ uninstallOutput.stdout_lines }}"

# windoze /cygdrive/c/Users/Administrator/AppData/Roaming/IBM/Installation Manager/uninstall/userinstc
# ansible_user: Administrator
- name:  uninstall Windoze ibm installation manager
  ignore_errors: true
  shell: "~/AppData/Roaming/IBM/Installation Manager/uninstall/userinstc"
  register: uninstallOutput
  failed_when: ( uninstallOutput.rc not in [ 0, 1 ] )
  when: 
  - ansible_system == 'Windows' or 'CYG' in ansible_system

- name:  uninstall *nix ibm installation manager
  ignore_errors: true
  shell: "~/var/ibm/InstallationManager/uninstall/uninstallc"
  register: uninstallOutput
  failed_when: ( uninstallOutput.rc not in [ 0, 1 ] )
  when: 
  - ansible_system != 'Windows' and 'CYG' not in ansible_system
  
- name: uninstallAll output
  debug: 
   msg: "{{ uninstallOutput.stdout_lines }}"

- name: Remove previous http dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ install_ihs_base }}/{{ shared_dir }}"
  - "{{ install_ihs_base }}/{{ http_dir }}"
  - "{{ install_ihs_base }}/{{ plugin_dir }}"
  - "{{ install_ihs_base }}/{{ wct_dir }}"
  - "{{ install_ihs_base }}/im_install"
  - "{{ install_ihs_base }}/IM"
  - "{{ install_ihs_base }}/javasharedresources"
  - "{{ install_ihs_base }}/im_http_plugin.xml"
  - "{{ install_ihs_base }}/im_liberty.xml"
  - "{{ install_ihs_base }}/wct_definition.xml"
  - "{{ install_ihs_base }}/https_conf"
  - "~/var/"
  - "~/etc/"
