---

- name: check for RedHat distribution
  fail:
    msg: Target OS is not RedHat
  when: ansible_distribution != "RedHat"

- name: create jmeter.log
  file:
    path: '{{ item }}'
    state: touch
    mode: '0755'
  with_items:
  - jmeter.log
  - jmeter.error

- name: kill rm any existing jmeter container
  containers.podman.podman_container:
    log_level: info
    name: jmeter
    hostname: jmeter_container
    privileged: no
    userns: keep-id
    image: "{{ svt_jmeter_image }}"
    state: absent # started created absent stopped present
  register: svtop

- debug:
   msg: '{{ svtop }}'

# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html#ansible-collections-containers-podman-podman-container-module
- name: operate on svt jmeter container
  containers.podman.podman_container:
    log_level: info
    name: jmeter
    hostname: jmeter_container
    privileged: no
    userns: keep-id
    image: "{{ svt_jmeter_image }}"
    state: "{{ jmeter_state }}" # started created absent stopped present
    restart: yes
    timezone: '{{ jmeter_tz }}'
    volume:
    - '/home/{{ ansible_user }}/jmeter.log:/jmeter/jmeter.log'
    - '/home/{{ ansible_user }}/jmeter.error:/jmeter/jmeter.error'
    command: "-script {{ jmeter_script_id }} \
              -host {{ jmeter_ihs_host }} \
              -port {{ jmeter_ihs_port }} \
              -protocol {{ jmeter_ihs_protocol }} \
              -duration {{ jmeter_duration }} \
              -rampUpSecs {{ jmeter_rampUpSecs }} \
              -threads {{ jmeter_threads }} \
              -auth {{ jmeter_auth }} \
              -appUrl {{ jmeter_appContext }} \
              -report {{ jmeter_report }}"
  register: svtop

- debug:
   msg: '{{ svtop }}'

- name: Gather facts for all containers
  containers.podman.podman_container_info:
  register: svtop
- debug:
   msg: '{{ svtop }}'
