galaxy_info:
  role_name: request_ocp_roks
  author: Jason Erickson
  description: Create a ROKS cluster in IBM Cloud
  company: IBM

  issue_tracker_url: https://github.ibm.com/dte/ansible-ibmcloud-roks-roles/issues

  min_ansible_version: 1.2

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  github_branch: master

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
  - name: Linux
    versions:
    - all

  galaxy_tags:
    - ibmcloud
    - openshift
    - roks

dependencies: []
