---

- name: BackupConfig on dmgr
  when: profile_type == 'dmgr'
  block:
   - name: Backup the dmgr config
     ansible.builtin.shell: "{{install_base }}/{{ twas_dir }}/profiles/{{ profile_name }}/bin/backupConfig.sh -nostop"
     register: backupConfigOutput
     failed_when: ( backupConfigOutput.rc not in [ 0, 255 ] )
   - name: BackupConfigOutput
     ansible.builtin.debug:
      msg: "{{ backupConfigOutput.stdout_lines }}"
