---
- name: Restart the apache http server gracefully
  tags: Restart 
  block:
  - name: check if apachectl is installed
    stat:
      path: "{{ install_ihs_base }}/{{ http_dir }}/bin/apachectl"
    register: ishttp
    failed_when: ishttp.stat.exists == False

  - name: HTTPServer graceful load new / updated config
    failed_when: false
    shell: "{{install_ihs_base }}/{{ http_dir }}/bin/apachectl graceful"
    register: gracefulOutput

  - name: apachectl gracefulOutput
    debug: 
     msg: "{{ gracefulOutput.stdout_lines }}"

  - name: check if adminctl is installed
    stat:
      path: "{{ install_ihs_base }}/{{ http_dir }}/bin/adminctl"
    register: ishttp
    failed_when: ishttp.stat.exists == False

  - name: HTTPServer adminctl graceful load new / updated config
    failed_when: false
    shell: "{{install_ihs_base }}/{{ http_dir }}/bin/adminctl graceful"
    register: gracefulOutput

  - name: adminctl gracefulOutput
    debug: 
     msg: "{{ gracefulOutput.stdout_lines }}"
