---
- name: daytrader8
  tags: daytrader8 
  block:
  - name: check if liberty is installed
    stat:
      path: "{{ install_base }}/{{ liberty_dir }}/bin/server"
    register: isliberty
    failed_when: isliberty.stat.exists == False

  - name: copy jvm.options template
    template:
     src: jvm.options.j2
     dest: "{{install_base }}/{{ liberty_dir }}/usr/servers/{{ wl_server }}/jvm.options"
  - name: copy server.xml template
    template:
     src: server.xml.j2
     dest: "{{install_base }}/{{ liberty_dir }}/usr/servers/{{ wl_server }}/server.xml"

  - name: copy application war
    copy:
      src: files/io.openliberty.sample.daytrader8.war
      dest: "{{install_base }}/{{ liberty_dir }}/usr/shared/apps/io.openliberty.sample.daytrader8.war"
      mode: '0755'

  - name: db2jars dir
    file:
      path: '{{ item }}'
      state: directory
      recurse: yes
    with_items:
    - "{{install_base }}/{{ liberty_dir }}/usr/shared/resources/db2jars"

  - name: copy db2jcc4.jar 
    copy:
      src: /tmp/db2jcc4.jar
      dest: "{{install_base }}/{{ liberty_dir }}/usr/shared/resources/db2jars/db2jcc4.jar"
      mode: '0755'
  - name: copy db2jcc_license_cu.jar 
    copy:
      src: /tmp/db2jcc_license_cu.jar
      dest: "{{install_base }}/{{ liberty_dir }}/usr/shared/resources/db2jars/db2jcc_license_cu.jar"
      mode: '0755'

  - name: autoAcceptCertificates
    lineinfile:
      path: "{{ install_base }}/{{ liberty_dir }}/usr/servers/{{ wl_server }}/server.env"
      regexp: 'autoAcceptCertificates'
      line: 'JVM_ARGS=-Dcom.ibm.websphere.collective.utility.autoAcceptCertificates=true'
