---
#https://www.ibm.com/docs/en/installation-manager/1.8.5?topic=line-command-arguments-imcl-command#r_tools__cic_selector
cic_selector_arch:
  chrp: 'ppc64'
  ppc64le: 'ppc64le'
  x86_64: 'x86_64'
  x86: 'x86'
  s390x: 's390x'
  001300055A28: 'ppc'
cic_selector_os:
  AIX: 'aix'
  Linux: 'linux'
  Windows: 'win32'
  CYGWIN_NT-10.0-20348: 'win32' # hard coded to a specific cygwin version
  ZOS: 'zos'
  OS400: 'os400'
# cmvc defect to get this fixed : 803544
im_twas855_java_package:
  chrp: ''
  ppc64le: 'com.ibm.jre.71_64bit'
  x86_64: 'com.ibm.jre.6_64bit'
  x86: ''
  s390x: ''
