---
- name: Install OCP+Beta Fyre cluster
  hosts: fyreApi
  roles:
  - role: request_ocp_fyre

- name: Install csi-cephfs and then common services onto OCP+Beta Fyre cluster
  hosts: ocp-clusters
  gather_facts: false
  roles:
  - role: git_install_fyre
  - role: csi_cephfs_fyre
  - role: common_services
