---
aws_access_key: " "  # your AWS_ACCESS_KEY_ID
aws_secret_key: " " # your AWS_SECRET_ACCESS_KEY
AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key}}"
AWS_REGION: "us-east-1"
WORKER_COUNT: 3
WORKER_VM_SIZE: m5.2xlarge # size of worker VM instances
MASTER_VM_SIZE: m5.2xlarge # sice of master VM instances
WORKER_VOLUME_SIZE: 256 # GB
MASTER_VOLUME_SIZE: 256 # GB
