---
cloud: aws
logfile: "/tmp/deploy.log"

# Master nodes 
"MASTER_CPUS": "10"
"MASTER_MEMORY": "32768"
"MASTER_DISK_SIZE": "300"
"MASTER_COUNT": 3

# Worker nodes
"WORKER_COUNT": 3
"WORKER_CPUS": "16"
"WORKER_MEMORY": "73728"
"WORKER_DISK_SIZE": "200"

"WORKER_VM_SIZE": "m5.2xlarge" # size of worker VM instances
"MASTER_VM_SIZE": "m5.2xlarge" # sice of master VM instances