---
install_base: '/home/nest'
liberty_dir: 'wlp'
wl_server: 'server'
min_heap: '1G'
max_heap: '3G'
cluster_name: 'DayTrader10'
db_user: 'db2inst1'
db_user1: 'db2inst1'
db_pass: 'guessme'
db_pass1: 'guessme'
db_host: 'dbhost'
db_host1: 'dbhost'
db_port: '50000'
db_port1: '50000'
db_name: 'tradedb'
# could be sessions if separate db
db_name1: 'tradedb' 
console_log_level: OFF
liberty_max_logs: 20
liberty_max_file_size: 20 # MB
