---
liberty_im_driver: 'cl240620240603-2001.31.linux'
liberty_daily_or_test: 'test'
shared_dir: 'IM-shared'
gsa_user: 'gsauser'
gsa_pass: 'gsapass'
ibm_user: 'external_ibmuser'
ibm_pass: 'external_ibmpass'
im_liberty_package: 'com.ibm.websphere.liberty.ND'
im_java_short_version: '21' # com.ibm.java.jdk.v17 com.ibm.java.jdk.v11, com.ibm.java.jdk.8
