---
twas_im_driver: 'f5202422.01'
twas_daily_or_test: 'test'
install_base: '/home/nest'
twas_dir: 'was'
app_dir: 'AppClient'
shared_dir: 'IM-shared'
gsa_user: 'gsauser'
gsa_pass: 'gsapass'
ibm_user: 'external_ibmuser'
ibm_pass: 'external_ibmpass'
#twas_release: 'WAS855'
twas_release: 'WAS90'

profile_templatePath:
  managed: '{{ install_base }}/{{ twas_dir }}/profileTemplates/managed'
  dmgr: '{{ install_base }}/{{ twas_dir }}/profileTemplates/management'
  default: '{{ install_base }}/{{ twas_dir }}/profileTemplates/default'

cellName: 'ndcell'
clusterName: 'Cluster'
appServerName: 'Server'

le_package_extension:
  chrp: ''
  ppc64le: '.le'
  x86_64: ''
  x86: ''
  s390x: ''
im_twas_package:
  WAS90: 'com.ibm.websphere.ND.v90'
  WAS855: 'com.ibm.websphere.ND{{le_package_extension[ansible_architecture]}}.v85'
im_appclient_package:
  WAS90: 'com.ibm.websphere.APPCLIENT.v90'
  WAS855: 'com.ibm.websphere.APPCLIENT{{le_package_extension[ansible_architecture]}}.v85'
im_twas_java_package: 'com.ibm.java.jdk.v8'
