---

install_base: '/home/nest'
twas_dir: 'was'

profile_templatePath:
  managed: '{{ install_base }}/{{ twas_dir }}/profileTemplates/managed'
  dmgr: '{{ install_base }}/{{ twas_dir }}/profileTemplates/management'

cellName: 'ndcell'
clusterName: 'Cluster'
serverName: 'Server'

le_package_extension:
  chrp: ''
  ppc64le: '.le'
  x86_64: ''
  x86: ''
  s390x: ''
im_twas_package:
  WAS90: 'com.ibm.websphere.ND.v90'
  WAS855: 'com.ibm.websphere.ND{{le_package_extension[ansible_architecture]}}.v85'
im_twas_java_package: 'com.ibm.java.jdk.v8'
