---
# AZURE SUBSCRIPTION INFORMATION
"AZURE_SUBSCRIPTIONID": " "
"AZURE_CLIENTID": " "
"AZURE_CLIENTSECRET": " "
"AZURE_TENANTID": " "
"AZURE_BASE_DOMAIN_RESOURCE_GROUP_NAME": " " #For example openshift4-terraform, look yours up on https://portal.azure.com or create one for your subscription.
# AZURE NODE INFORMATION
"AZURE_WORKER_DISK_SIZE": 256 # See https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types
"AZURE_WORKER_TYPE": "Standard_D8s_v3" # See https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-sizes-specs
"AZURE_WORKER_COUNT": 3
"AZURE_MASTER_DISK_SIZE": 128 #See https://docs.microsoft.com/en-us/azure/virtual-machines/disks-types
"AZURE_MASTER_TYPE": "Standard_D4s_v3" #See https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-sizes-specs
"AZURE_REGION": eastus  #See
# SERvICE PRINCIPAL JSON - DO NOT CHANGE
"AZURE_SERVICE_PRINCIPAL": " "
