---
ihs_im_driver: "{{ twas_im_driver | default('f5192409.01', true) }}"
ihs_daily_or_test: "{{ twas_daily_or_test | default('test', true) }}"
twas_release: 'WAS90' # WAS855
install_ihs_base: "{{ install_base | default('/home/nest', true) }}"
# trick the template to install onto windoze via cygwin
install_base_win: ''
http_dir: 'HTTPServer'
plugin_dir: 'Plugins'
wct_dir: 'WCT'
webNode: 'webnode'
webServerName: 'webserver1'
shared_dir: 'IM-shared'
gsa_user: 'gsauser'
gsa_pass: 'gsapass'
ihs_http_port: '8180'
ihs_https_port: '9444'
ihs_admin_port: '8008'
ihs_admin_user: 'ihsadmin'
ihs_admin_pass: 'pihsadmin'
le_package_extension:
  chrp: ''
  ppc64le: '.le'
  x86_64: ''
  x86: ''
  s390x: ''
im_wct_package: 
  WAS90: 'com.ibm.websphere.WCT.v90'
  WAS855: 'com.ibm.websphere.WCT{{le_package_extension[ansible_architecture]}}.v85'
im_wct_java_package: 'com.ibm.java.jdk.v8'
im_plugin_package: 
  WAS90: 'com.ibm.websphere.PLG.v90'
  WAS855: 'com.ibm.websphere.PLG{{le_package_extension[ansible_architecture]}}.v85'
im_plugin_java_package: 'com.ibm.java.jdk.v8'
im_http_package: 
  WAS90: 'com.ibm.websphere.IHS.v90'
  WAS855: 'com.ibm.websphere.IHS{{le_package_extension[ansible_architecture]}}.v85'
im_http_java_package: 'com.ibm.java.jdk.v8'
