namespace: "ibm_community_automation"
name: "ibm_community_automation"
version: "1.0.0"
readme: "README.md"
authors:
    - "Ray Ashworth"
    - "Walter Krapohl"
    - "Steven Schader"
    - "Chris Webster"
    - "xcliu-ca"
    - "Jason Erickson"
    - "Mark Vardy"
    - "Prajyot Parab"
    - "Thomas Aley"
    - "Steve Martinelli"
    - "Afzal Chishti"
#    - "Author2 (https://author2.example.com)"
#    - "Author3 <author3@example.com>"
dependencies:
#    "other_namespace.collection1": ">=1.0.0"
#    "other_namespace.collection2": ">=2.0.0,<3.0.0"
#    "anderson55.my_collection": "*"    # note: "*" selects the highest version available
license:
    - "Apache-2.0"
tags:
#    - demo
#    - collection
repository: "https://github.com/IBM/community-automation/tree/master/ansible"