---
- name: Manage OCP Cluster(s) using Hive Instance
  hosts: bastion
  vars_files:
    - common-vars.yml
    - "{{ cloud }}-vars.yml"

  environment:
    PATH: ".:{{ ansible_env.PATH }}"

  roles:
    - role: aws_route53
      when: 'cloud == "vsphere" and admin_task != "delete"'

    - role: hive_ocp_cluster_provision

    - role: ocp_cluster_tag
      when: 'admin_task == "provision" and cloud != "vsphere" and cloud != "google"'

    - role: hive_ocp_cluster_delete
      when: 'admin_task == "delete"'

  tasks:

    - name: Display cluster details
      command: cat {{ CLUSTER_NAME }}_details.log
      register: cluster_details
      when: 'admin_task == "provision"'

    - name: Print details
      debug:
        msg: "{{ cluster_details.stdout }}"
      when: 'admin_task == "provision"'

    - set_fact:
        route_task: "delete"
      when: 'cloud == "vsphere" and admin_task == "delete"'

    - name: Run aws_route53 delete - vsphere only
      include_role:
        name: aws_route53
      when: 'cloud == "vsphere" and route_task == "delete"'

    - name: Clean kubevols - vsphere only
      include_role:
        name: clean_vmware_kubevols
      when: 'cloud == "vsphere" and admin_task == "delete"'
