---

- name: Create FyreVM with appropriate spec
  include_role: 
   name: fyrevm_provision
  vars:
   fyre_platform: x
   fyre_cpu: 2 
   fyre_memory: 4
   fyre_os: 'RedHat 9.2'
   fyre_site: "{{ site }}"
   fyre_comment: 'Pentest Host'
   clusterName_prefix: pentest
   target_group: pentest
