---
twas_im_driver: 'cf212205.01'
install_base: '/home/nest'
twas_dir: 'was'
shared_dir: 'IM-shared'
gsa_user: 'gsauser'
gsa_pass: 'gsapass'
ibm_user: 'external_ibmuser'
ibm_pass: 'external_ibmpass'
daily_or_test: 'test'
twas_release: 'WAS855' 
#twas_release: 'WAS90' 
