---

cs_setup_dir: ~/setup-files/cs-setup
cs_operator_name: ibm-common-service-operator
cs_operator_project_name: common-service
cs_subscription_channel: stable-v1
cs_subscription_strategy: Automatic
cs_operand_list: [] # leave empty list by default enable all operands. support name and pattern. example for cpd ["licensing","metering","commonui","iam"]
cs_operand_to_disable: ["elastic"] # support name and pattern to disable operands
storageclass_name: ""
strict_validation: true
