---

- name: set jmeter host specs
  no_log: "{{ noLog }}"
  vars:
  ## crc host specs
  - arch: x
  - numcpu: 2
  - memory: 2 # GB memory Fyre hosting VM
  - fos: 'Redhat 8.2'
  - comment: 'RH Jmeter'
  - localclusterName: "{{ clusterName }}"
  include_tasks:
    file: jmeter_fyrevm.yml
